### ISSUE TITLE
UX: Meeting with CEE editorial to understand stock replies and research guides

### ISSUE THREAD

**Issue by grange85** [nationalarchives/findability#5] opened 2018-08-22 10:59 UTC
- [x] Set up meeting with Matt N (and Sarah C, Chrissy ?)
- [x] Prepare a list of questions that we can put to them

Useful links 
[CEE stock replies](https://narnia/display/CEE/CEE+stock+replies)
[PMO stock replies](https://narnia/display/CORARC/PMO+Stock+Text)
[Research Guides](http://www.nationalarchives.gov.uk/help-with-your-research/research-guides-keywords/)

**Comment by cariannewhitworth** [comment] 2018-08-22 16:33
Hello! I've put a meeting in for Helen and I to meet Matt and Chrissy tomorrow (Sarah's on holiday) just to introduce them to the project and explain how our thinking so far is leaning towards the 'how do I find...' part of user's research journey (to start with), and how research guides fit into that.

Some things I'd like to talk to them about (pls add if you think of more):

- Jo's research says most almost half of enquiries end up in a user being directed to a research guide. Users aren't finding them, but record specialists think they're really useful. Do they feel that's still valid?
- If we were to look at the personas that were created a few years ago, which persona uses the guides most - or perhaps it's better to ask HOW each persona might find them useful (ie. do they read the whole thing, or parts of it. Are different parts useful in different contexts)?
- What is a generic research guide's content structure, roughly - can we sketch it? Is this relatively uniform across all guides?
- Simon mentioned that some users want help with understanding a digital record AFTER they've purchased it. Do guides cover 'how to interpret/understand records', or just how to locate them?
- What thoughts/ideas/common problems have they identified? And how/to what extent do CEE editorial want to be involved in this explore?

**Comment by catherinelliott** [comment] 2018-08-23 08:54
- I'd suggest also floating the idea of breaking up the research guides into more manageable sized pieces that can more easily be tied to relevant parts of relevant journeys and more easily absorbed by users.  Do we still have them whole somewhere but also break out the most relevant/useful/used parts of them to integrate into journeys?

**Comment by catherinelliott** [comment] 2018-08-23 09:53
Yes, I think that's good for short term and then medium/long term it's worth considering better ways of presenting the useful information held within the research guides.  There may be a couple of different ways to access the guidance such as a chat bot but we could also create a public facing knowledge base which has divided the information within the research guides into bite sized pieces combined with step by step guides and videos to give people options of how to consume the information.  

We should then use machine learning to connect the right help information to the right stages of journeys & parts of the website so people know they'll find the right answers/info presented to them when they need it. Otherwise people can search within the knowledge base for the help they need.

**Comment by Helen-Creeke** [comment] 2018-08-23 10:35
As part of the mix - CEE views on:
- if volume and/or type queries change over time - any relationship to how Discovery has evolved?
- why are the Research Guides valued for resolving queries, do the guides work as intended?
- what queries require the most effort? 

To explore Andy's memory of there being an early Discovery prompt asking users what they were looking for, a person or a place and why it was taken away (maybe 5 years ago?).

**Comment by cariannewhitworth** [comment] 2018-08-23 15:47
Today's meetings were really good, ta to all involved. Some outcomes:

- Sarra, Andy and I discussed resolving the 'where are the research guides' problem by thinking about adding a link to it somewhere. The Discovery help button is on every page, we also discussed rehashing this instead: do a card sort on the content (potentially by something like 'how to understand archives / how to understand Discovery / how to do your research) and redesigning the button ('Search help' instead?)... more info to follow. 

- CEE have lots and lots of knowledge about user/search probs and were really keen to get involved. 
- They are on board with bringing a research guide link into Discovery and said why not rename it to 'search help' right now. They would be good to involve in a card sort probably, and could tell us what content the help pages should include (but don't) and what's out of date. 
- Andy raised a good point that we should rename the button AFTER we've made the content good, otherwise people will click on it, find it's the same, and not click on it again. 

- Slightly separate note but another big problem that Matt raised was how they get lots of calls from people who haven't realised they've found the thing they're looking for, because they don't realise THAT IS THE THING (they're expecting to see a record, not a catalogue description). We talked about how we might use design/content to help users distinguish that that was the end of that particular search journey, but the beginning of a new one - actually accessing the record itself. 

-

**Closed** 2018-09-07 13:42 UTC
Labels: help wanted, objective, user-insight
